#' insert_index_sheet()
#'
#' @description Function which generates an index sheet inside an openxlsx workbook.
#' @param wb A workbook object as generated by openxlsx::createWorkbook()
#' @param logo Either statzh or zh, or path to logo file
#' @param contact Either "statzh" or a character string
#' @param homepage statzh or a character string with the URL
#' @param openinghours statzh or a character string or vector with opening hours
#' @param titlesource Character vector denoting the data source
#' @param auftrag_id Order ID
#' @param maintitle Title shown on index sheet
#' @param sheetname Name of Index Sheet
#' @param date_prefix Text prepended to date
#' @param order_id_prefix Text prepended to order ID
#' @export
#' @keywords datasetsXLSX
insert_index_sheet <- function(wb, logo = "statzh", contact = "statzh",
                               homepage = "statzh", openinghours = "statzh",
                               titlesource, auftrag_id, maintitle,
                               sheetname = "Index",
                               date_prefix = "Erstellt am: ",
                               order_id_prefix = "Auftragsnr.:",
                               toc_caption = "Inhalt"){

  # Initialize new worksheet as index sheet ------
  openxlsx::addWorksheet(wb, sheetname)


  # Insert logo ----------
  logo <- inputHelperLogoPath(logo)
  if (!is.null(logo)){
    openxlsx::insertImage(wb, sheetname, logo, 2.145, 0.7865, units = "in")
  }


  # Insert contact info, title, metadata, and sources into worksheet --------
  ### Contact information
  contact_info <- c(inputHelperContactInfo(contact),
                    inputHelperHomepage(homepage))
  openxlsx::writeData(wb, sheetname, contact_info, 15, 2,
                      name = "contact")

  ### Office hours
  openxlsx::writeData(wb, sheetname, inputHelperOfficeHours(openinghours),
                      18, getNamedRegionFirstRow(wb, sheetname, "contact"),
                      name = "officehours")

  ### Request information
  info_vec <- c(inputHelperDateCreated(prefix = date_prefix),
                inputHelperOrderNumber(auftrag_id, prefix = order_id_prefix))
  openxlsx::writeData(wb, sheetname, info_vec, 15,
                      getNamedRegionLastRow(wb, sheetname, "contact"),
                      name = "info")
  ### Add Headerline
  openxlsx::addStyle(wb, sheetname, style_headerline(),
                     getNamedRegionLastRow(wb, sheetname, "info"), 1:20,
                     gridExpand = TRUE, stack = TRUE)

  ### Title
  openxlsx::writeData(wb, sheetname, maintitle, 3,
                      getNamedRegionLastRow(wb, sheetname, "info") + 3,
                      name = "title")
  openxlsx::addStyle(wb, sheetname, style_maintitle(),
                     getNamedRegionLastRow(wb, sheetname, "title"), 3)

  ### Source
  openxlsx::writeData(wb, sheetname, titlesource, 3,
                      getNamedRegionLastRow(wb, sheetname, "title") + 1,
                      name = "source")

  ### Table of content caption
  openxlsx::writeData(wb, sheetname, toc_caption, 3,
                      getNamedRegionLastRow(wb, sheetname, "source"),
                      name = "toc")
  openxlsx::addStyle(wb, sheetname, subtitleStyle(),
                     getNamedRegionLastRow(wb, sheetname, "toc"), 3)


  # Format ---------
  ### Set column width of first column to 1
  openxlsx::setColWidths(wb, sheetname, 1, 1)

  ### Hide gridlines
  openxlsx::showGridLines(wb, sheetname, FALSE)
}
