#' insert_index_sheet()
#'
#' @description Function which generates an index sheet inside an openxlsx workbook.
#' @param wb A workbook object as generated by openxlsx::createWorkbook()
#' @param logo Either statzh or zh, or path to logo file
#' @param contact Either "statzh" or a character string
#' @param homepage statzh or a character string with the URL
#' @param openinghours statzh or a character string or vector with opening hours
#' @param titlesource Character vector denoting the data source
#' @param auftrag_id Order ID
#' @param maintitle Main title
#' @keywords datasetsXLSX
insert_index_sheet <- function(wb, logo, contact, homepage, openinghours,
                               titlesource, auftrag_id, maintitle){

  ## Create index sheet
  openxlsx::addWorksheet(wb, sheetName = "Inhalt")

  ## Content
  #-----------

  ### Logo
  if(!is.null(logo)){
    logo <- prep_logo(logo)

    if (file.exists(logo)){
      openxlsx::insertImage(wb, sheet = "Inhalt", file = logo, width = 2.145,
                            height = 0.7865, units = "in")
    } else {
      message("no logo found.")
    }
  }


  ### Contact information
  if(!is.null(contact)){
    openxlsx::writeData(wb, sheet = "Inhalt", x = prep_contact(contact),
                        xy = c("O", 2))
  }

  if(!is.null(homepage)){
    openxlsx::writeData(wb, sheet = "Inhalt", x = prep_homepage(homepage),
                        xy = c("O", 5))
  }

  if(!is.null(openinghours)){
    openxlsx::writeData(wb, sheet = "Inhalt",
                        x = prep_openinghours(openinghours), xy = c("R", 2))
  }

  ### Creation date
  openxlsx::writeData(wb, sheet = "Inhalt", x = prep_creationdate(),
                      xy = c("O", 8))

  ### Order id
  if (!is.null(auftrag_id)){
    openxlsx::writeData(wb, sheet = "Inhalt", x = prep_orderid(auftrag_id),
                        xy = c("O", 9))
  }

  ### Title
  openxlsx::writeData(wb, sheet = "Inhalt", x = maintitle,
                      headerStyle = mainTitleStyle(), xy = c("C", 10))

  ### Source
  if (!is.null(titlesource)){
    openxlsx::writeData(wb, sheet = "Inhalt", x = prep_source(titlesource),
                        xy = c("C", 11))
  }

  ### Content caption
  openxlsx::writeData(wb, sheet = "Inhalt", x = "Inhalt",
                      headerStyle = subtitleStyle(), xy = c("C", 13))


  ## Format
  #-----------------

  ### Hide gridlines
  openxlsx::showGridLines(wb, sheet = "Inhalt", showGridLines = FALSE)

  ### Set column widths
  openxlsx::setColWidths(wb, sheet = "Inhalt", cols = 1, widths = 1)


  ### Add Headerline
  openxlsx::addStyle(wb, sheet = "Inhalt", style = style_headerline(),
                     rows = 6, cols = 1:20, gridExpand = TRUE, stack = TRUE)


  ### Apply style to Maintitle
  openxlsx::addStyle(wb, sheet = "Inhalt", style = mainTitleStyle(), rows = 10,
                     cols = 3, gridExpand = TRUE)


  ### Apply style to Subtitle
  openxlsx::addStyle(wb, sheet = "Inhalt", style = subtitleStyle(), rows = 14,
                     cols = 3, gridExpand = TRUE)
}
